##### CLASH CONFIG v2 BY @efrzz ####

redir-port: 9797
tproxy-port: 0
# socks-port: 7891
# mixed-port: 7893
mode: rule
log-level: warning
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
# secret: '123456'
bind-address: "*"

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:1053
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
  - "*.lan"
  - "*.ntp.*"
  # - "*.localdomain"
  # - "*.example"
  # - "*.invalid"
  # - "*.localhost"
  # - "*.test"
  # - "*.local"
  # - "*.home.arpa"
  nameserver:
  - "9.9.9.9#PROXY"
  proxy-server-nameserver:
  # xl dns
  - 112.215.203.248
  - 112.215.203.254
  - '[2400:9800:2:2::245]'
  - '[2400:9800:2:2::246]'
  
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
  
tun:
  enable: true
  device: utun
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
  - any:53
  - tcp://any:53
  auto-route : true
  auto-detect-interface: true

ping-url:
  # - &ping "http://ping.xmbb.net"
  # - &ping "http://www.gstatic.com/generate_204"
  - &ping "http://clients3.google.com"

proxies:
proxy-groups:
  - name: "PROXY"
    type: select
    use:
      - "provide"
    proxies:
      - "FALLBACK"
      - "BEST-PING"
      
  - name: "FALLBACK"
    type: fallback
    use: 
      - "provide"
  
  - name: "BEST-PING"
    type: url-test
    use: 
      - "provide"
    url: *ping
    interval: 300
    
  - name: "ADBLOCK"
    type: select
    proxies:
      - "REJECT"
      - "PROXY"
      
proxy-providers:
  "provide":
    type: file
    url: https://raw.githubusercontent.com/efrzz/clash-config/main/provider/proxy-provider.yaml
    path: ./proxy-provider.yaml
    healthcheck:
      enable: true
      url: *ping
      interval: 300

rule-providers:
  "Ads":
    type: http
    behavior: classical
    path: "./rule_provider_BlockAds.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
    
rules:
  - RULE-SET,Ads,ADBLOCK
  - MATCH,PROXY
